name: Packer

on:
  pull_request:
    branches:
        - main

jobs:
  packer-validate-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compress entire repo
      run: |
        zip -r webapp.zip . -x "*.git*" "webapp/*" "node_modules/*"
    
    - name: Setup packer
      uses: hashicorp/setup-packer@main

    - name: Init packer
      run: packer init -var-file="./packer/variables.pkr.hcl" ./packer/ami.pkr.hcl

    - name: Run packer format to check 
      run: packer fmt -check -var-file="./packer/variables.pkr.hcl" ./packer/ami.pkr.hcl
           
    - name: Run packer validate
      run: packer validate -var-file="./packer/variables.pkr.hcl" ./packer/ami.pkr.hcl
